permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: kongdd
  email: kongdd@mail2.sysu.edu.cn
  weibo: http://weibo.com/orangeissweet
  github: http://github.com/kongdd


# 站点信息
title: 孔冬冬的博客
description: My personal blog

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: kongdd

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - R language
  - 学校事物

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

highlighter: pygments